name = "Neat"
uuid = "ca4da33f-684f-4f20-8ad8-db35abfaaa8c"
authors = ["Musa Ozcetin <musa.oezcetin@campus.tu-berlin.de>"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
CSV = "0.10"
GraphRecipes = "0.5.14"
Plots = "1.40.16"
PlutoUI = "0.7.68"
Random = "1.11.0"
Revise = "3.8.0"
julia = "1.11"
